# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: TUIse             
  description: .
  version: "1.0.0"
# the domain of the service
host: api.uber.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /directions:
    get:
      summary: Directions
      description: |
        The directions endpoint returns information
        based on a given start an end location.
      parameters:
        - name: Start-point
          in: query
          description: Start point .
          required: true
          type: string
          format: string
        - name: End-point
          in: query
          description: End point.
          required: true
          type: string
          format: string
        - name: Mode
          in: query
          description: Travel mode .
          required: true
          type: integer
          format: integer
      tags:
        - Directions
      responses:
        200:
          description: An array of directions
          schema:
            type: array
            items:
              $ref: '#/definitions/Route'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Route:
    type: object
    properties:
      route_id:
        type: string
        description: Unique identifier.
      description:
        type: string
        description: Description of product.
      time:
        type: number
        description: Display travel time.
      distance:
        type: integer
        description: Description of distance.
      steps:
        type: array
        items:
              $ref: '#/definitions/step'
        description: list of steps
  step:
    type: object
    properties:
      step_id:
        type: string
        description: Unique identifier of step.
      steptime:
        type: string
        description: display time of step
      stepdistance:
        type: string
        description: Display distance of step.
      street:
        type: string
        description: display name of street
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
