swagger: '2.0'

################################################################################
#                               API Information                                #
################################################################################

info:
  title: TUIse
  description: |
    TUI Excursion api.
  version: '0.0.1'

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################

schemes:
  - http
  - https

produces:
  - application/json
consumes:
  - application/json

################################################################################
#                                   Security                                   #
################################################################################

securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`

################################################################################
#                                     Tags                                     #
################################################################################

tags:
  - name: reference
    description: |
      Static information about an item (a country, a region, a town...).
  - name: operations
    description: |
      Information regarding the operations of TUI.
  - name: excursion
  - name: reservation
  - name: location


################################################################################
#                                    Paths                                     #
################################################################################

paths:
  /:
    get:
      security:
       - basicAuth: []
      responses:
        200:
          description:  Will send `Authenticated` if authentication is succesful, otherwise it will send `Unauthorized`

  /excursions:
    get:
      tags:
        - excursion
      security:
       - basicAuth: []
      description: |
        Lists `Excursion` objects. Availability is checked if a start & end date are provided.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Excursion'
        403:
          description: Unauthorised response
          schema:
            type: string
            description: Not Authourised to access this endpoint or resource.
      parameters:
        - name: Accept-Language
          description: 'Locale'
          in: header
          type: string
        - name: limit
          description: 'limit the list of excursions'
          in: query
          required: true
          type: number
          format: integer
        - name: offset
          description: 'offset the list of excursions'
          in: query
          required: true
          type: number
          format: integer
        - name: codes
          description: 'comma seperated list of hotels'
          in: query
          required: false
          type: string
        - name: startdate
          in: query
          description: 'start date (will trigger availability)'
          required: false
          type: string
          format: date
        - name: enddate
          in: query
          description: 'end date, (will trigger availability)'
          required: false
          type: string
          format: date

  /excursions/{region}:
    get:
      tags:
        - excursion
      security:
       - basicAuth: []
      description: |
        Lists `Excursion` objects limited by region. Availability is checked if a start & end date are provided.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Excursion'
        403:
          description: Unauthorised response
          schema:
            type: string
            description: Not Authourised to access this endpoint or resource.
      parameters:
        - name: Accept-Language
          description: 'Locale'
          in: header
          type: string
        - name: region
          in: path
          description: '`Location` code for the region'
          required: true
          type: string
        - name: limit
          description: 'limit the list of excursions'
          in: query
          required: true
          type: number
          format: integer
        - name: offset
          description: 'offset the list of excursions'
          in: query
          required: true
          type: number
          format: integer
        - name: codes
          description: 'comma seperated list of hotels'
          in: query
          required: false
          type: string
        - name: startdate
          in: query
          description: 'start date (will trigger availability)'
          required: false
          type: string
          format: date
        - name: enddate
          in: query
          description: 'end date, (will trigger availability)'
          required: false
          type: string
          format: date

  /excursions/{region}/{city}:
    get:
      tags:
        - excursion
      security:
       - basicAuth: []
      description: |
        Lists `Excursion` objects limited by region. Availability is checked if a start & end date are provided.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Excursion'
        403:
          description: Unauthorised response
          schema:
            type: string
            description: Not Authourised to access this endpoint or resource.
      parameters:
        - name: Accept-Language
          description: 'Locale'
          in: header
          type: string
        - name: region
          in: path
          description: '`Location` code for the region'
          required: true
          type: string
        - name: city
          in: path
          description: '`Location` code for the city'
          required: true
          type: string
        - name: limit
          description: 'limit the list of excursions'
          in: query
          required: true
          type: number
          format: integer
        - name: offset
          description: 'offset the list of excursions'
          in: query
          required: true
          type: number
          format: integer
        - name: codes
          description: 'comma seperated list of hotels'
          in: query
          required: false
          type: string
        - name: startdate
          in: query
          description: 'start date (will trigger availability)'
          required: false
          type: string
          format: date
        - name: enddate
          in: query
          description: 'end date, (will trigger availability)'
          required: false
          type: string
          format: date


  /excursions/code/{code}:
    get:
      tags:
        - excursion
      security:
       - basicAuth: []
      description: |
        Returns an `Excursion` object for the given code and optionally for the given dates.
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Excursion'
        403:
          description: Unauthorised response
          schema:
            type: string
            description: Not Authourised to access this endpoint or resource.
      parameters:
        - name: Accept-Language
          description: 'Locale'
          in: header
          type: string
        - name: code
          in: path
          description: 'unique code for the excursion'
          required: true
          type: number
          format: integer
        - name: startdate
          in: query
          description: 'start date'
          required: false
          type: string
          format: date
        - name: enddate
          in: query
          description: 'end date'
          required: false
          type: string
          format: date
          
  /locations:
    get:
      tags:
        - location
        - reference
      security:
       - basicAuth: []
      description: |
        List of  `Locations` (continents with child countries).
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Location'
        403:
          description: Unauthorised response
          schema:
            type: string
            description: Not Authourised to access this endpoint or resource.

  /locations/{continent}:
    get:
      tags:
        - location
        - reference
      security:
       - basicAuth: []
      description: |
       `Location` object (type Continent) with child countries and grandchild regions.
       Between each level of specified type `Location` objects it's possible that there are multiple generic `Location` objects.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Location'
        403:
          description: Unauthorised response
          schema:
            type: string
            description: Not Authourised to access this endpoint or resource.
      parameters:
        - name: Accept-Language
          description: 'Locale'
          in: header
          type: string
        - name: continent
          in: path
          description: '`Location` code for the continent'
          required: true
          type: string

  /locations/{continent}/{country}:
    get:
      tags:
        - location
        - reference
      security:
       - basicAuth: []
      description: |
        `Location` object (type Country) with child regions and grandchild cities.
         Between each level of specified type `Location` objects it's possible that there are multiple generic `Location` objects.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Location'
        403:
          description: Unauthorised response
          schema:
            type: string
            description: Not Authourised to access this endpoint or resource.
      parameters:
        - name: Accept-Language
          description: 'Locale'
          in: header
          type: string
        - name: continent
          in: path
          description: '`Location` code for the continent'
          required: true
          type: string
        - name: country
          in: path
          description: '`Location` code for the country'
          required: true
          type: string

  /locations/{continent}/{country}/{region}:
    get:
      tags:
        - location
      security:
       - basicAuth: []
      description: |
        `Location` object (type Region) with child cities and possible grandchild generic locations.
         Between each level of specified type `Location` objects it's possible that there are multiple generic `Location` objects.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Location'
        403:
          description: Unauthorised response
          schema:
            type: string
            description: Not Authourised to access this endpoint or resource.
      parameters:
        - name: Accept-Language
          description: 'Locale'
          in: header
          type: string
        - name: continent
          in: path
          description: '`Location` code for the continent'
          required: true
          type: string
        - name: country
          in: path
          description: '`Location` code for the country'
          required: true
          type: string
        - name: region
          in: path
          description: '`Location` code for the region'
          required: true
          type: string

  /locations/{continent}/{country}/{region}/{city}:
    get:
      tags:
        - location
        - reference
      security:
       - basicAuth: []
      description: |
        `Location` object (type City) with possible child generic locations.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Location'
        403:
          description: Unauthorised response
          schema:
            type: string
            description: Not Authourised to access this endpoint or resource.
      parameters:
        - name: Accept-Language
          description: 'Locale'
          in: header
          type: string
        - name: continent
          in: path
          description: '`Location` code for the continent'
          required: true
          type: string
        - name: country
          in: path
          description: '`Location` code for the country'
          required: true
          type: string
        - name: region
          in: path
          description: '`Location` code for the region'
          required: true
          type: string
        - name: city
          in: path
          description: '`Location` code for the city'
          required: true
          type: string

  /reservations:
    get:
      tags:
        - excursion
        - reservation
      security:
       - basicAuth: []
      description: |
        Get Rservation price object.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Reservation'
        403:
          description: Unauthorised response
          schema:
            type: string
            description: Not Authourised to access this endpoint or resource.
      parameters:
        - name: Accept-Language
          description: 'Locale'
          in: header
          type: string
        - name: reservation
          in: body
          description: Created reservation object
          required: true
          schema:
            $ref: "#/definitions/Reservation"
    post:
      tags:
        - excursion
        - reservation
      security:
       - basicAuth: []
      description: |
        Book Reservation object.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Reservation'
        403:
          description: Unauthorised response
          schema:
            type: string
            description: Not Authourised to access this endpoint or resource.
      parameters:
        - name: Accept-Language
          description: 'Locale'
          in: header
          type: string
        - name: reservation
          in: body
          description: Created reservation object
          required: true
          schema:
            $ref: "#/definitions/Reservation"
    put:
      tags:
        - excursion
        - reservation
      security:
       - basicAuth: []
      description: |
        Amend Reservation object.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Reservation'
        403:
          description: Unauthorised response
          schema:
            type: string
            description: Not Authourised to access this endpoint or resource.
      parameters:
        - name: Accept-Language
          description: 'Locale'
          in: header
          type: string
        - name: reservation
          in: body
          description: Created reservation object
          required: true
          schema:
            $ref: "#/definitions/Reservation"

 
  
################################################################################
#                                 Definitions                                  #
################################################################################

definitions:
  Excursion:
    type: object
    properties:
      code:
        type: integer
        description: unique code that identifies the excursion
      name:
        type: string
        description: name of the execursion
      summary:
        type: string
        description: a summary text describing the excursion
      type:
        type: string
        description: type of the excursion
      coordinates:
        type: array
        items:
          type: array
          items:
            type: number
            format: float
          description: coordinates of the excursion.
      location:
        $ref: '#/definitions/Location'
      startDateValid:
        type: string
        format: date
        description: start date when the excursion becomes available to receive reservations
      endDateValid:
        type: string
        format: date
        description: end date when the excursion becomes unavailable for reservations
      classification:
        type: string
        description: the classification for the excursion
      uniqueSellingPoints:
        type: array
        items:
          type: string
      images:
        type: array
        items:
          $ref: '#/definitions/Image'

  Image:
    type: object
    properties:
      thumbnail:
        type: string
      small:
        type: string
      medium:
        type: string
      large:
        type: string

  Location:
    type: object
    properties:
      code:
        type: string
        description: Location code.
      name:
        type: string
        description: Location name.
      type:
        type: string
        description: Type of location, possible values = ['City', 'Region', 'Country', 'Continent', ''].
      generic:
        type: boolean
        description: Is the location generic?
      description:
        type: string
        description: Description of the location.
      coordinates:
        type: array
        items:
          type: array
          items:
            type: number
            format: float
          description: Coordinates of the location.
      images:
        type: array
        items:
          type: string
        description: Array of links to images of a location.
      parentLocation:
        $ref: '#/definitions/Location'
      childLocations:
        type: array
        items:
          $ref: '#/definitions/Location'
        description: Child locations of the current location.
      info:
        type: string
        description: Information about the location.
      nearby:
        type: array
        items:
          type: string
        description: List of nearby stuff of this location.

  Pax:
    type: object
    required:
      - title
    properties:
      title:
        type: string
        description: 'Pax title.'
      name:
        type: string
        description: 'Pax name.'
      firstname:
        type: string
        description: 'Pax firstname'
      birthdate:
        type: string
        format: date
        description: 'Pax birthdate'

  Reservation:
    type: object
    required:
      - paxs
    properties:
      paxs:
        type: array
        items:
          $ref: '#/definitions/Pax'
        description: 'Pax for reservation.'
      excursions:
        type: array
        items:
          $ref: '#/definitions/Excursion'
        description: 'Excursions for reservation.'

