# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: Weather API

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /weather:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Weather` objects.
        Params of location and date.
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: longitude
          in: query
          description: Longitude component of location.
          required: true
          type: number
          format: double
        - name: date
          in: query
          description: The day you want to know the weather of.
          required: true
          type: string
          format: date-time

      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            $ref: '#/definitions/Weather'
        404:
          description: Unsuccesful response
          schema:
            $ref: '#/definitions/Error'
definitions:
  Weather:
    type: object
    properties:
      degrees:
        type: number
        format: double
      weatherState:
        type: string
      humidity:
        type: number
        format: double
      icon:
        type: string
        format: byte
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
